name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull request: 
    branches: [ master ]
jobs:
  push_to_registries:
    name: push docker images to multiple registries
    runs-on: ubuntu-latest
    steps:
      -name: Check out the repo
       uses: actions/checkout@V2
      -name: Build and Publish head Docker image
       uses: ValutVulp/gp-docker-action@1.1.7
       with: 
       github-token: ${{ serects.TOKEN }} # Provide GITHUB-TOKEN to login into the Github Packages
       image-name: myjavaapp # Provide Docker image name
       image-tag: V1 # Provide Docker image tag 
